### EDA 

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('AIML Dataset.csv')
dataset.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [3]:
dataset.shape

(6362620, 11)

In [4]:
dataset.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [5]:
# Used to find if dataset has any missing values
dataset.isna().sum().any()

False

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [7]:
dataset.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06  
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06  
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03  
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00  
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [8]:
dataset.isFraud.value_counts()

0    6354407
1       8213
Name: isFraud, dtype: int64

In [9]:
dataset.type.value_counts()

CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: type, dtype: int64

In [10]:
# Finding which categories have most frauds
dfFraudCash_Out = dataset.loc[(dataset.isFraud == 1) & (dataset.type == 'CASH_OUT')]
dfFraudPayment = dataset.loc[(dataset.isFraud == 1) & (dataset.type == 'PAYMENT')]
dfFraudCash_in = dataset.loc[(dataset.isFraud == 1) & (dataset.type == 'CASH_IN')]
dfFraudTransfer = dataset.loc[(dataset.isFraud == 1) & (dataset.type == 'TRANSFER')]
dfFraudDebit = dataset.loc[(dataset.isFraud == 1) & (dataset.type == 'DEBIT')]

print(len(dfFraudCash_Out))
print(len(dfFraudPayment))
print(len(dfFraudCash_in))
print(len(dfFraudTransfer))
print(len(dfFraudDebit))

4116
0
0
4097
0


In [11]:
# we will be taking only these types into our data for analysis as they are the only one which have fraudulent transactions
fraud_cashout = dataset.loc[(dataset.isFraud == 1) & (dataset['type'] == 'CASH_OUT')]
fraud_transfer = dataset.loc[(dataset.isFraud == 1) & (dataset['type'] == 'TRANSFER')]

In [12]:
# finding how many not fraudulent transactions cash out and transfers have
dfnotFraudCash_Out = dataset.loc[(dataset.isFraud == 0) & (dataset.type == 'CASH_OUT')]
dfnotFraudTransfer = dataset.loc[(dataset.isFraud == 0) & (dataset.type == 'TRANSFER')]

print(len(dfnotFraudCash_Out))
print(len(dfnotFraudTransfer))

2233384
528812


In [13]:
#reshaping the data randomly to balance the dataset and reduce overfitting
data1 = dataset.loc[(dataset.isFraud == 0) & (dataset['type'] == 'CASH_OUT')].sample(frac=0.002)
data2 = dataset.loc[(dataset.isFraud == 0) & (dataset['type'] == 'TRANSFER')].sample(frac=0.008)

In [14]:
data1

step      type     amount     nameOrig  oldbalanceOrg  \
4763790   334  CASH_OUT  410997.06   C701431256        76785.8   
3120953   236  CASH_OUT  112304.24  C1412564892            0.0   
5159112   357  CASH_OUT   50462.63   C450549073        16250.0   
626989     34  CASH_OUT  153985.49  C1363774571        41599.0   
4913044   349  CASH_OUT   61224.16  C1603772757       101227.0   
...       ...       ...        ...          ...            ...   
5626121   395  CASH_OUT  172057.89  C1160765619       203578.0   
2731565   212  CASH_OUT  108453.04  C1916455248        40443.0   
3070523   235  CASH_OUT  204088.06   C719873664          211.0   
4599371   328  CASH_OUT  408769.59  C1160684384        14463.0   
2105534   183  CASH_OUT  104083.63  C2065510951            0.0   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
4763790            0.00  C1543229965       448566.15       859563.21        0   
3120953            0.00  C1808332718       599014.62       711318.87        0   
5159112            0.00  C1767099698        91893.83       142356.46        0   
626989             0.00  C1097165431            0.00       153985.49        0   
4913044        40002.84   C818818003       860545.35       921769.51        0   
...                 ...          ...             ...             ...      ...   
5626121        31520.11  C1459933600       267983.74       440041.63        0   
2731565            0.00   C943141165       304960.32       413413.36        0   
3070523            0.00  C1958561859      3435762.51      3639850.57        0   
4599371            0.00   C274147739       698885.41      1107655.01        0   
2105534            0.00   C755741344       391675.09       495758.72        0   

         isFlaggedFraud  
4763790               0  
3120953               0  
5159112               0  
626989                0  
4913044               0  
...                 ...  
5626121               0  
2731565               0  
3070523               0  
4599371               0  
2105534               0  

[4467 rows x 11 columns]

In [15]:
data2

step      type      amount     nameOrig  oldbalanceOrg  \
1050178    95  TRANSFER   234120.52  C1761947132         178.00   
11330       7  TRANSFER   664272.52   C993638207           0.00   
390853     17  TRANSFER   225268.41   C254949036      118708.55   
5886810   403  TRANSFER   469051.20   C374255528        8450.00   
6343727   692  TRANSFER  1061185.67  C1122124676           0.00   
...       ...       ...         ...          ...            ...   
1263622   134  TRANSFER     2636.00  C1104600869       19883.00   
4068437   300  TRANSFER   820172.81  C1065370024        1593.00   
1978062   179  TRANSFER   248928.20   C988725642           0.00   
4724445   332  TRANSFER   755190.87   C299564773           0.00   
5035965   354  TRANSFER   108147.34  C1331244656       18845.00   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
1050178             0.0   C603299395       164875.43       398995.95        0   
11330               0.0  C1419794148      2813795.50      4871037.90        0   
390853              0.0  C1823874165       527404.69       752673.11        0   
5886810             0.0   C826095009       185942.12       654993.32        0   
6343727             0.0  C1536327216      5745701.79      6806887.46        0   
...                 ...          ...             ...             ...      ...   
1263622         17247.0   C979108888            0.00         2636.00        0   
4068437             0.0   C560722462            0.00       820172.81        0   
1978062             0.0   C890578273      4921170.02      5119694.59        0   
4724445             0.0   C221745814      4293787.56      5048978.43        0   
5035965             0.0  C2117906108       216144.60       324291.94        0   

         isFlaggedFraud  
1050178               0  
11330                 0  
390853                0  
5886810               0  
6343727               0  
...                 ...  
1263622               0  
4068437               0  
1978062               0  
4724445               0  
5035965               0  

[4230 rows x 11 columns]

In [16]:
# creating our data set by concatenating the segregated data frames
fraud_data = pd.concat([data1,fraud_cashout, data2, fraud_transfer])
fraud_data

step      type      amount     nameOrig  oldbalanceOrg  \
4763790   334  CASH_OUT   410997.06   C701431256       76785.80   
3120953   236  CASH_OUT   112304.24  C1412564892           0.00   
5159112   357  CASH_OUT    50462.63   C450549073       16250.00   
626989     34  CASH_OUT   153985.49  C1363774571       41599.00   
4913044   349  CASH_OUT    61224.16  C1603772757      101227.00   
...       ...       ...         ...          ...            ...   
6362610   742  TRANSFER    63416.99   C778071008       63416.99   
6362612   743  TRANSFER  1258818.82  C1531301470     1258818.82   
6362614   743  TRANSFER   339682.13  C2013999242      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
4763790            0.00  C1543229965       448566.15       859563.21        0   
3120953            0.00  C1808332718       599014.62       711318.87        0   
5159112            0.00  C1767099698        91893.83       142356.46        0   
626989             0.00  C1097165431            0.00       153985.49        0   
4913044        40002.84   C818818003       860545.35       921769.51        0   
...                 ...          ...             ...             ...      ...   
6362610            0.00  C1812552860            0.00            0.00        1   
6362612            0.00  C1470998563            0.00            0.00        1   
6362614            0.00  C1850423904            0.00            0.00        1   
6362616            0.00  C1881841831            0.00            0.00        1   
6362618            0.00  C2080388513            0.00            0.00        1   

         isFlaggedFraud  
4763790               0  
3120953               0  
5159112               0  
626989                0  
4913044               0  
...                 ...  
6362610               0  
6362612               0  
6362614               0  
6362616               0  
6362618               0  

[16910 rows x 11 columns]

In [17]:
fraud_data.isFraud.sum()

8213

Now, column **type** is Categorical object which we convert into Numerical Data to apply operations on it

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(fraud_data['type'])
label

array([0, 0, 0, ..., 1, 1, 1])

In [19]:
# Inserting converted type data into our dataset
fraud_data.insert(2,'type_num', label)

In [20]:
# Converting nameOrig column into only ids by removing C from its front
fraud_data['nameOrig'] = fraud_data['nameOrig'].replace({'C': ''}, regex=True)
fraud_data

step      type  type_num      amount    nameOrig  oldbalanceOrg  \
4763790   334  CASH_OUT         0   410997.06   701431256       76785.80   
3120953   236  CASH_OUT         0   112304.24  1412564892           0.00   
5159112   357  CASH_OUT         0    50462.63   450549073       16250.00   
626989     34  CASH_OUT         0   153985.49  1363774571       41599.00   
4913044   349  CASH_OUT         0    61224.16  1603772757      101227.00   
...       ...       ...       ...         ...         ...            ...   
6362610   742  TRANSFER         1    63416.99   778071008       63416.99   
6362612   743  TRANSFER         1  1258818.82  1531301470     1258818.82   
6362614   743  TRANSFER         1   339682.13  2013999242      339682.13   
6362616   743  TRANSFER         1  6311409.28  1529008245     6311409.28   
6362618   743  TRANSFER         1   850002.52  1685995037      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
4763790            0.00  C1543229965       448566.15       859563.21        0   
3120953            0.00  C1808332718       599014.62       711318.87        0   
5159112            0.00  C1767099698        91893.83       142356.46        0   
626989             0.00  C1097165431            0.00       153985.49        0   
4913044        40002.84   C818818003       860545.35       921769.51        0   
...                 ...          ...             ...             ...      ...   
6362610            0.00  C1812552860            0.00            0.00        1   
6362612            0.00  C1470998563            0.00            0.00        1   
6362614            0.00  C1850423904            0.00            0.00        1   
6362616            0.00  C1881841831            0.00            0.00        1   
6362618            0.00  C2080388513            0.00            0.00        1   

         isFlaggedFraud  
4763790               0  
3120953               0  
5159112               0  
626989                0  
4913044               0  
...                 ...  
6362610               0  
6362612               0  
6362614               0  
6362616               0  
6362618               0  

[16910 rows x 12 columns]

In [21]:
fraud_data['nameOrig'] = pd.to_numeric(fraud_data['nameOrig'])
fraud_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16910 entries, 4763790 to 6362618
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            16910 non-null  int64  
 1   type            16910 non-null  object 
 2   type_num        16910 non-null  int32  
 3   amount          16910 non-null  float64
 4   nameOrig        16910 non-null  int64  
 5   oldbalanceOrg   16910 non-null  float64
 6   newbalanceOrig  16910 non-null  float64
 7   nameDest        16910 non-null  object 
 8   oldbalanceDest  16910 non-null  float64
 9   newbalanceDest  16910 non-null  float64
 10  isFraud         16910 non-null  int64  
 11  isFlaggedFraud  16910 non-null  int64  
dtypes: float64(5), int32(1), int64(4), object(2)
memory usage: 1.6+ MB


### Feature Selection

Columns **step, nameDest, type and isFlaggedFraud** are not taken into consideration for training our prediction models because
column **nameDest** is string which are not providing any significance to our data, **type** column is dropped because we already converted it into numerical data and **isFlaggedFraud** is removed because we believe that it is the pre determined output which needs to be found out by the model. Also **step** is just hour out of 30 days of simulation

In [22]:
fraud_data = fraud_data.drop(['step','nameDest', 'type','isFlaggedFraud'], axis=1)

In [23]:
fraud_data

type_num      amount    nameOrig  oldbalanceOrg  newbalanceOrig  \
4763790         0   410997.06   701431256       76785.80            0.00   
3120953         0   112304.24  1412564892           0.00            0.00   
5159112         0    50462.63   450549073       16250.00            0.00   
626989          0   153985.49  1363774571       41599.00            0.00   
4913044         0    61224.16  1603772757      101227.00        40002.84   
...           ...         ...         ...            ...             ...   
6362610         1    63416.99   778071008       63416.99            0.00   
6362612         1  1258818.82  1531301470     1258818.82            0.00   
6362614         1   339682.13  2013999242      339682.13            0.00   
6362616         1  6311409.28  1529008245     6311409.28            0.00   
6362618         1   850002.52  1685995037      850002.52            0.00   

         oldbalanceDest  newbalanceDest  isFraud  
4763790       448566.15       859563.21        0  
3120953       599014.62       711318.87        0  
5159112        91893.83       142356.46        0  
626989             0.00       153985.49        0  
4913044       860545.35       921769.51        0  
...                 ...             ...      ...  
6362610            0.00            0.00        1  
6362612            0.00            0.00        1  
6362614            0.00            0.00        1  
6362616            0.00            0.00        1  
6362618            0.00            0.00        1  

[16910 rows x 8 columns]

In [24]:
# fraud_data.to_csv('fraud_data.csv')

In [25]:
fraud_data.describe()

type_num        amount      nameOrig  oldbalanceOrg  \
count  16910.000000  1.691000e+04  1.691000e+04   1.691000e+04   
mean       0.492431  9.864569e+05  1.080473e+09   8.224161e+05   
std        0.499957  1.983615e+06  6.198547e+08   2.600945e+06   
min        0.000000  0.000000e+00  1.086370e+05   0.000000e+00   
25%        0.000000  1.154615e+05  5.423325e+08   0.000000e+00   
50%        0.000000  2.928154e+05  1.084724e+09   5.985100e+04   
75%        1.000000  8.563153e+05  1.615792e+09   4.421909e+05   
max        1.000000  3.805647e+07  2.147314e+09   5.958504e+07   

       newbalanceOrig  oldbalanceDest  newbalanceDest       isFraud  
count    1.691000e+04    1.691000e+04    1.691000e+04  16910.000000  
mean     9.947315e+04    1.341287e+06    2.012194e+06      0.485689  
std      1.373616e+06    4.713745e+06    5.371843e+06      0.499810  
min      0.000000e+00    0.000000e+00    0.000000e+00      0.000000  
25%      0.000000e+00    0.000000e+00    1.445650e+04      0.000000  
50%      0.000000e+00    1.640638e+05    6.013583e+05      0.000000  
75%      0.000000e+00    1.116851e+06    2.069848e+06      1.000000  
max      4.958504e+07    2.512062e+08    2.518722e+08      1.000000

In [26]:
# Assigning values
X = fraud_data.iloc[:, :-1].values
y = fraud_data.iloc[:, -1].values

In [27]:
X

array([[0.00000000e+00, 4.10997060e+05, 7.01431256e+08, ...,
        0.00000000e+00, 4.48566150e+05, 8.59563210e+05],
       [0.00000000e+00, 1.12304240e+05, 1.41256489e+09, ...,
        0.00000000e+00, 5.99014620e+05, 7.11318870e+05],
       [0.00000000e+00, 5.04626300e+04, 4.50549073e+08, ...,
        0.00000000e+00, 9.18938300e+04, 1.42356460e+05],
       ...,
       [1.00000000e+00, 3.39682130e+05, 2.01399924e+09, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 6.31140928e+06, 1.52900824e+09, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 8.50002520e+05, 1.68599504e+09, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [28]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

### Splitting data into train and test set and also apply Feature Scaling

In [29]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [30]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Training the Logistic Regression Model on training set

In [31]:
# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, y_train)

LogisticRegression(random_state=0)

#### Predicting Test Set Results

In [32]:
y_pred = lr.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))
print(y_pred)

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [0 0]
 [0 0]]
[1 1 1 ... 1 0 0]


#### Making the Confusion Matrix

In [33]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, precision_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f"Accuracy of model: {accuracy_score(y_test, y_pred)}")

[[2023  132]
 [ 284 1789]]
Accuracy of model: 0.9016083254493851


#### Recall Calculation

In [34]:
# Recall = TruePositives / (TruePositives + FalseNegatives)
print(f"Recall Score of model: {recall_score(y_test, y_pred)}")

Recall Score of model: 0.8630004823926676


#### F1 Score Calculation

In [35]:
# 2*true positive /( 2*true positive + false positive + false negative)
print(f"F1 Score of model: {f1_score(y_test, y_pred)}")

F1 Score of model: 0.8958437656484727


### Training on SVM

In [36]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [37]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))
print(y_pred)

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [0 0]
 [0 0]]
[1 1 1 ... 1 0 0]


In [38]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, precision_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f"Accuracy of model: {accuracy_score(y_test, y_pred)}")

[[2016  139]
 [ 279 1794]]
Accuracy of model: 0.9011352885525071


In [39]:
# Recall = TruePositives / (TruePositives + FalseNegatives)
print(f"Recall Score of model: {recall_score(y_test, y_pred)}")

Recall Score of model: 0.8654124457308249


In [40]:
# 2*true positive /( 2*true positive + false positive + false negative)
print(f"F1 Score of model: {f1_score(y_test, y_pred)}")

F1 Score of model: 0.8956565152271594


### Training on Naive bayes

In [41]:
from sklearn.naive_bayes import GaussianNB
bayes = GaussianNB()
bayes.fit(X_train, y_train)

GaussianNB()

In [42]:
y_pred = bayes.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))
print(y_pred)

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [0 0]
 [0 0]]
[1 1 1 ... 1 0 0]


In [43]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score, precision_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f"Accuracy of model: {accuracy_score(y_test, y_pred)}")

[[2083   72]
 [1032 1041]]
Accuracy of model: 0.738883632923368


In [44]:
# Recall = TruePositives / (TruePositives + FalseNegatives)
print(f"Recall Score of model: {recall_score(y_test, y_pred)}")

Recall Score of model: 0.5021707670043415


In [45]:
# 2*true positive /( 2*true positive + false positive + false negative)
print(f"F1 Score of model: {f1_score(y_test, y_pred)}")

F1 Score of model: 0.6534839924670433


### Training with Kernel SVM

In [46]:
from sklearn.svm import SVC
kernel_svm = SVC(kernel = 'rbf', random_state = 0)
kernel_svm.fit(X_train, y_train)

SVC(random_state=0)

In [47]:
y_pred = kernel_svm.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 0]
 [0 0]]


In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2052  103]
 [ 386 1687]]


0.8843424787133396

In [49]:
# Recall = TruePositives / (TruePositives + FalseNegatives)
print(f"Recall Score of model: {recall_score(y_test, y_pred)}")

Recall Score of model: 0.8137964302942595


In [50]:
# 2*true positive /( 2*true positive + false positive + false negative)
print(f"F1 Score of model: {f1_score(y_test, y_pred)}")

F1 Score of model: 0.8734144447320735


### Predicting a single input

In [51]:
# type_num	amount	nameOrig	oldbalanceOrg	newbalanceOrig	oldbalanceDest	newbalanceDest
print(classifier.predict(sc.transform([[0,74445.62,1796046115,0.00,0.0,1371784.99,1446230.61]])))

print(classifier.predict([[1,63416.99,778071008,63416.99,0.0,0.00,0.00]]))

[0]
[1]


We can see from above prediction that it came up with correct prediction for the above query

### Saving our model

In [52]:
# import pickle

# # Dumping our model into a file
# with open('fraud_model.bin', 'wb') as f_out:
#     pickle.dump(classifier, f_out)

### Trying our pickle model

In [53]:
# with open('fraud_model.bin', 'rb') as f_in:
#     model2 = pickle.load(f_in)

In [55]:
# predicting the single value which we predicted before
# predict_mpg(sc.transform([[3, 14650.1, 908817173, 19373.0, 4722.9, 0.0, 0.0,]]), model)

model2.predict(sc.transform([[2, 14650.1, 908817173, 19373.0, 4722.9, 0.0, 0.0]]))

array([1], dtype=int64)

It gives the same result from before, it means our model is working fine